### ISSUE TITLE
自用ios版ipa包分享

### ISSUE THREAD

**Issue by lchypwx** [mikai233/fstar-client#3]
小程序用不了了，就自己改了个ios的出来，自行签名即可使用
仅修改了几行必须要修改的代码（别的我也不会
第一次接触flutter和ios开发，非常简陋还有很多bug，敬请谅解
若侵权请联系我删除
https://pan.baidu.com/s/1mBjD4oNggr-RBoEP6ZYdjQ?pwd=5l4g

**Comment by mikai233** [comment]
可以的，我并没有iOS的机器，代码里面有些功能并没有做多平台处理
